### ISSUE TITLE
Collect "Labels"

### ISSUE THREAD

**Issue by dimitrisnl** [appsignal/appsignal-kubernetes#52]
Labels are key-value pairs attached to Kubernetes resources (like Pods & Nodes)

- They are used to identify attributes of resources that are meaningful and relevant to users (e.g., app=frontend, env=production, tier=backend).
- Labels do not provide uniqueness. Many objects can share the same label.

Some examples:
- `app=nginx`, 
- `owner=team-a`, 
- `billing=project-x`, 
- `env=dev`. 
  
**So it's a catch-all solution that each Organization can tweak to their needs.** 

Example
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    env: production
    tier: frontend
```

---

So let's collect the `metadata.labels` from each resource we can. It's a single key-map value. 

This will allow some powerful filtering/grouping on the front-end side. 

[Docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)
