### ISSUE TITLE
Collect `ownerReferences` 

### ISSUE THREAD

**Issue by dimitrisnl** [appsignal/appsignal-kubernetes#53]
Currently, we only collect the namespace field and group Pods by it. However grouping solely by namespace is too broad for many use cases

We should also collect `metadata.ownerReferences` from each Pod. This field allows us to identify the higher-level controller (e.g., Deployment, Job, StatefulSet) that owns the Pod. 

[Docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/)

--- 

examples:

```yaml
# owned by a Deployment
apiVersion: v1
kind: Pod
metadata:
  name: frontend-abc123
  namespace: production
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: frontend-7fbd7c6cc9
      uid: 123456
```

```yaml
# owned by a Job
apiVersion: v1
kind: Pod
metadata:
  name: data-import-xyz456
  namespace: batch-jobs
  ownerReferences:
    - apiVersion: batch/v1
      kind: Job
      name: data-import
      uid: 789012
```

```yaml
# unmanaged
apiVersion: v1
kind: Pod
metadata:
  name: debug-shell
  namespace: tools
  ownerReferences: []
```
